[phases.setup]
cmds = [
    "pip install python-telegram-bot==13.7 --force-reinstall --no-cache-dir",
]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
]

[start]
cmd = "python main.py"